CREATE DATABASE mileage;

-- \c mileage

CREATE TABLE Carros(
  id SERIAL PRIMARY KEY NOT NULL,
  modelo VARCHAR(255) NOT NULL,
  marca VARCHAR(255) NOT NULL,
  motor VARCHAR(255) NOT NULL,
  piloto VARCHAR(255) NOT NULL
);
